theme: jekyll-theme-minimal
title: Mapping The Mind Maze
description: The human brain, with its complex networks and cognitive processes, remains a scientific mystery. In our quest to uncovering those details, we turn to an innovative approach: analyzing player behavior in the Wikispeedia game. The game where players move through Wikipedia articles to reach a goal helps us study how people process new information and make quick decisions, giving us a closer look into the most intuitive conenctions in their brain.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
